package export

// The expected values in this file were recorded from the earlier Qt version
// of Kvit Notes, given the same inputs.

import (
	"strings"
	"testing"
)

// qtExports are Markdown bodies with the <body> of the page the exporter
// writes for each, and the plain text it writes.
var qtExports = []struct{ md, body, text string }{
	{"Hello",
		"<p>Hello</p>",
		"Hello\n"},
	{"# Getting Started\n\nA **bold** and *italic* and [link](http://x).",
		"<h1 id=\"getting-started\">Getting Started</h1><p>A <strong>bold</strong> and <em>italic</em> and <a href=\"http://x\">link</a>.</p>",
		"# Getting Started\n\nA bold and italic and link.\n"},
	{"[click me](javascript:danger) [a](https://example.com/p) [a](mailto:x@y.z) [a](#frag) [x](JaVaScRiPt:y)",
		"<p>click me <a href=\"https://example.com/p\">a</a> <a href=\"mailto:x@y.z\">a</a> <a href=\"#frag\">a</a> x</p>",
		"click me a a a x\n"},
	{"2 \\* 3 \\* 4 and \\# and \\| and \\\\ and \\_x\\_",
		"<p>2 * 3 * 4 and # and | and \\ and _x_</p>",
		"2 * 3 * 4 and # and | and \\ and _x_\n"},
	{"- one\n- two\n\n1. a\n2. b",
		"<ul><li>one</li><li>two</li></ul><ol><li>a</li><li>b</li></ol>",
		"- one\n\n- two\n\n1. a\n\n2. b\n"},
	{"- [ ] open\n- [x] done 📅 2026-07-15 ⏫",
		"<ul><li>&#9744; open</li><li>&#9745; done 📅 2026-07-15 ⏫</li></ul>",
		"[ ] open\n\n[x] done 📅 2026-07-15 ⏫\n"},
	{"> quoted\n> more\n>\n> after blank",
		"<blockquote>quoted<br>more<br><br>after blank</blockquote>",
		"> quoted\n> more\n> \n> after blank\n"},
	{"> a\n> > nested\n> > deeper\n> back",
		"<blockquote>a</blockquote><blockquote>nested<br>deeper</blockquote><blockquote>back</blockquote>",
		"> a\n\n> nested\n> deeper\n\n> back\n"},
	{"> [!info] Heads up\n> body\n> more body",
		"<div class=\"callout\"><div class=\"title\">Heads up</div>body<br>more body</div>",
		"[INFO] Heads up\n  body\n  more body\n"},
	{"> [!warning]- Folded title  <!--kvit color=#2970c8-->\n> text",
		"<div class=\"callout\" style=\"border-left-color:#2970c8\"><div class=\"title\" style=\"color:#2970c8\">Folded title</div>text</div>",
		"[WARNING] Folded title\n  text\n"},
	{"> [!tip]\n> untitled",
		"<div class=\"callout\"><div class=\"title\">tip</div>untitled</div>",
		"[TIP]\n  untitled\n"},
	{"wrapped\nline\n\n- one\n  two\n\n**bold**\nafter",
		"<p>wrapped<br>line</p><ul><li>one<br>two</li></ul><p><strong>bold</strong><br>after</p>",
		"wrapped\nline\n\n- one\ntwo\n\nbold\nafter\n"},
	{"---\n\n***\n\n---  <!--kvit style=dashed thickness=4-->\n\n---  <!--kvit width=50% color=crimson-->\n\n---  <!--kvit style=decorative color=#abc-->",
		"<hr><hr><hr style=\"border-top-width:4px;border-top-style:dashed\"><hr style=\"border-top-color:crimson;width:50%;margin-left:auto;margin-right:auto\"><div class=\"hr-deco\"><hr style=\"border-top-color:#abc\"><span class=\"dia\" style=\"color:#abc\">&#9670;</span><hr style=\"border-top-color:#abc\"></div>",
		"---\n\n---\n\n---\n\n---\n\n---\n"},
	{"```python\ndef f(x):\n    \"\"\"doc\n    more\"\"\"\n    return x + 1  # c\n@dec\nclass A: pass\n```",
		"<pre><code><span style=\"color:#a626a4\">def</span> <span style=\"color:#4078f2\">f</span>(x):\n    <span style=\"color:#50a14f\">&quot;&quot;&quot;doc</span>\n<span style=\"color:#50a14f\">    more&quot;&quot;&quot;</span>\n    <span style=\"color:#a626a4\">return</span> x + <span style=\"color:#986801\">1</span>  <span style=\"color:#a0a1a7\"># c</span>\n<span style=\"color:#4078f2\">@dec</span>\n<span style=\"color:#a626a4\">class</span> A: <span style=\"color:#a626a4\">pass</span></code></pre>",
		"def f(x):\n    \"\"\"doc\n    more\"\"\"\n    return x + 1  # c\n@dec\nclass A: pass\n"},
	{"```go\npackage main\n\nfunc main() { x := `raw` ; y := 0x1F; fmt.Println(\"hi\", 3.5e10) }\n```",
		"<pre><code><span style=\"color:#a626a4\">package</span> main\n\n<span style=\"color:#a626a4\">func</span> <span style=\"color:#4078f2\">main</span>() { x := <span style=\"color:#50a14f\">`raw`</span> ; y := <span style=\"color:#986801\">0x1F</span>; fmt.<span style=\"color:#4078f2\">Println</span>(<span style=\"color:#50a14f\">&quot;hi&quot;</span>, <span style=\"color:#986801\">3.5e10</span>) }</code></pre>",
		"package main\n\nfunc main() { x := `raw` ; y := 0x1F; fmt.Println(\"hi\", 3.5e10) }\n"},
	{"```js\nconst a = /* c */ 1;\n/* multi\nline */ let s = `t${a}`;\nfoo(a)\n```",
		"<pre><code><span style=\"color:#a626a4\">const</span> a = <span style=\"color:#a0a1a7\">/* c */</span> <span style=\"color:#986801\">1</span>;\n<span style=\"color:#a0a1a7\">/* multi</span>\n<span style=\"color:#a0a1a7\">line */</span> <span style=\"color:#a626a4\">let</span> s = <span style=\"color:#50a14f\">`t${a}`</span>;\n<span style=\"color:#4078f2\">foo</span>(a)</code></pre>",
		"const a = /* c */ 1;\n/* multi\nline */ let s = `t${a}`;\nfoo(a)\n"},
	{"```cpp\n#include <x>\nint main() { return 0; } // end\n```",
		"<pre><code><span style=\"color:#a626a4\">#include</span> &lt;x&gt;\n<span style=\"color:#4078f2\">int</span> <span style=\"color:#4078f2\">main</span>() { <span style=\"color:#a626a4\">return</span> <span style=\"color:#986801\">0</span>; } <span style=\"color:#a0a1a7\">// end</span></code></pre>",
		"#include <x>\nint main() { return 0; } // end\n"},
	{"```sql\nSELECT * FROM t WHERE a = 'it''s' -- c\n```",
		"<pre><code><span style=\"color:#a626a4\">SELECT</span> * <span style=\"color:#a626a4\">FROM</span> t <span style=\"color:#a626a4\">WHERE</span> a = <span style=\"color:#50a14f\">'it''s'</span> <span style=\"color:#a0a1a7\">-- c</span></code></pre>",
		"SELECT * FROM t WHERE a = 'it''s' -- c\n"},
	{"```bash\necho $HOME ${USER} \"q\"  # c\n```",
		"<pre><code><span style=\"color:#4078f2\">echo</span> <span style=\"color:#4078f2\">$HOME</span> <span style=\"color:#4078f2\">${USER}</span> <span style=\"color:#50a14f\">&quot;q&quot;</span>  <span style=\"color:#a0a1a7\"># c</span></code></pre>",
		"echo $HOME ${USER} \"q\"  # c\n"},
	{"```html\n<!-- c -->\n<a href=\"x\" class='y'>&amp;</a>\n```",
		"<pre><code><span style=\"color:#a0a1a7\">&lt;!-- c --&gt;</span>\n&lt;<span style=\"color:#a626a4\">a</span> <span style=\"color:#4078f2\">href</span>=<span style=\"color:#50a14f\">&quot;x&quot;</span> <span style=\"color:#4078f2\">class</span>=<span style=\"color:#50a14f\">'y'</span>&gt;<span style=\"color:#986801\">&amp;amp;</span>&lt;/<span style=\"color:#a626a4\">a</span>&gt;</code></pre>",
		"<!-- c -->\n<a href=\"x\" class='y'>&amp;</a>\n"},
	{"```css\n@media x { .a #fff { color: #fff !important; width: 10px; } }\n```",
		"<pre><code><span style=\"color:#a626a4\">@media</span> x { <span style=\"color:#4078f2\">.a</span> <span style=\"color:#986801\">#fff</span> { <span style=\"color:#4078f2\">color</span>: <span style=\"color:#986801\">#fff</span> <span style=\"color:#a626a4\">!important</span>; <span style=\"color:#4078f2\">width</span>: <span style=\"color:#986801\">10px</span>; } }</code></pre>",
		"@media x { .a #fff { color: #fff !important; width: 10px; } }\n"},
	{"```markdown\n# H\n- item\n1. num\n> q\n`code` [l](u)\n```\n",
		"<pre><code><span style=\"color:#a626a4\"># H</span>\n<span style=\"color:#4078f2\">-</span> item\n<span style=\"color:#4078f2\">1.</span> num\n<span style=\"color:#a0a1a7\">&gt; q</span>\n<span style=\"color:#50a14f\">`code`</span> [l]<span style=\"color:#4078f2\">(u)</span></code></pre>",
		"# H\n- item\n1. num\n> q\n`code` [l](u)\n"},
	{"```json\n{\"a\": [1, true, null]}\n```",
		"<pre><code>{<span style=\"color:#50a14f\">&quot;a&quot;</span>: [<span style=\"color:#986801\">1</span>, <span style=\"color:#a626a4\">true</span>, <span style=\"color:#a626a4\">null</span>]}</code></pre>",
		"{\"a\": [1, true, null]}\n"},
	{"```rust\nfn main() { let v: Vec<i32> = Vec::new(); }\n```",
		"<pre><code><span style=\"color:#a626a4\">fn</span> <span style=\"color:#4078f2\">main</span>() { <span style=\"color:#a626a4\">let</span> v: <span style=\"color:#4078f2\">Vec</span>&lt;<span style=\"color:#4078f2\">i32</span>&gt; = <span style=\"color:#4078f2\">Vec</span>::<span style=\"color:#4078f2\">new</span>(); }</code></pre>",
		"fn main() { let v: Vec<i32> = Vec::new(); }\n"},
	{"```unknownlang\nplain <text>\n```",
		"<pre><code>plain &lt;text&gt;</code></pre>",
		"plain <text>\n"},
	{"```diagram\n┌────┐\n│ <a>│\n└────┘\n```",
		"<pre class=\"text-diagram\"><code>┌────┐\n│ &lt;a&gt;│\n└────┘</code></pre>",
		"┌────┐\n│ <a>│\n└────┘\n"},
	{"```mermaid\nflowchart LR\n  A[<x>] --> B\n```\n\n```mermaid\ngraph TD\nC-->D\n```",
		"<pre class=\"mermaid\">flowchart LR\n  A[&lt;x&gt;] --&gt; B</pre><details class=\"diagram-source\"><summary>Diagram source</summary><pre><code>flowchart LR\n  A[&lt;x&gt;] --&gt; B</code></pre></details><pre class=\"mermaid\">graph TD\nC--&gt;D</pre><details class=\"diagram-source\"><summary>Diagram source</summary><pre><code>graph TD\nC--&gt;D</code></pre></details>",
		"[mermaid diagram]\nflowchart LR\n  A[<x>] --> B\n\n[mermaid diagram]\ngraph TD\nC-->D\n"},
	{"# Intro\n\n```toc\nstale\n```\n\n## Details\n\n### Deep\n\n# Intro\n\n## Details",
		"<h1 id=\"intro\">Intro</h1><ul class=\"toc\"><li style=\"margin-left:0px\"><a href=\"#intro\">Intro</a></li><li style=\"margin-left:16px\"><a href=\"#details\">Details</a></li><li style=\"margin-left:32px\"><a href=\"#deep\">Deep</a></li><li style=\"margin-left:0px\"><a href=\"#intro-1\">Intro</a></li><li style=\"margin-left:16px\"><a href=\"#details-1\">Details</a></li></ul><h2 id=\"details\">Details</h2><h3 id=\"deep\">Deep</h3><h1 id=\"intro-1\">Intro</h1><h2 id=\"details-1\">Details</h2>",
		"# Intro\n\nIntro\n  Details\n    Deep\nIntro\n  Details\n\n## Details\n\n### Deep\n\n# Intro\n\n## Details\n"},
	{"```kanban\n## To do\n- [ ] Ship the beta #release #\"client work\" 📅 2026-08-01\n  Needs the installer signed first\n\n  second para\n- [x] Write \\#notes <!--kvit created=2026-07-20-->\n## Done\n```",
		"<div class=\"kanban\"><div class=\"col\"><strong>To do</strong> <span class=\"count\">2</span><div class=\"card\"><div class=\"title\">&#9744; Ship the beta</div><div class=\"meta\">Needs the installer signed first<br><br>second para</div><div class=\"meta\"><span class=\"chip\">release</span><span class=\"chip\">client work</span><span class=\"chip\">&#128197; 2026-08-01</span></div></div><div class=\"card\"><div class=\"title\">&#9745; Write #notes</div></div></div><div class=\"col\"><strong>Done</strong> <span class=\"count\">0</span></div></div>",
		"To do (2)\n  [ ] Ship the beta  #release  #client work  (due 2026-08-01)\n      Needs the installer signed first\n\n      second para\n  [x] Write #notes\n\nDone (0)\n"},
	{"```query\nfrom: Projects/\nwhere: status = active\n```",
		"<pre><code>from: Projects/\nwhere: status = active</code></pre>",
		"from: Projects/\nwhere: status = active\n"},
	{"$$\na & b < c > d\n$$\n\nInline $x^2$ and $5 and $6 and $a$.",
		"<p class=\"math-display\">\\[ a &amp; b &lt; c &gt; d \\]</p><p>Inline \\(x^2\\) and $5 and $6 and \\(a\\).</p>",
		"a & b < c > d\n\nInline x^2 and $5 and $6 and a.\n"},
	{"$$x^2$$",
		"<p class=\"math-display\">\\[ x^2 \\]</p>",
		"x^2\n"},
	{"| A | B |\n| :--- | ---: |\n| 1 | `a|b` |\n| **x** | y<br>z |",
		"<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>`a</td></tr><tr><td><strong>x</strong></td><td>y<br>z</td></tr></table>",
		"A | B\n--+----\n1 | `a\nx | y z\n"},
	{"| A | B |  <!--kvit cols=120,0-->\n| --- | --- |\n| 1 | 2 |",
		"<table><colgroup><col style=\"width:120px\"><col></colgroup><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>",
		"A | B\n--+--\n1 | 2\n"},
	{"![cat](https://example.com/cat.png \"a caption\")\n\n![](https://example.com/wiki)\n\n![clip](video.mp4)\n\n![](missing.png)",
		"<figure><img alt=\"cat\" src=\"https://example.com/cat.png\"><figcaption>a caption</figcaption></figure><div class=\"embed\"><div class=\"title\"><a href=\"https://example.com/wiki\">https://example.com/wiki</a></div></div><p>&#9654; <a href=\"video.mp4\">clip</a></p><figure><em>[image: missing.png]</em></figure>",
		"[image: cat] https://example.com/cat.png\n  a caption\n\n[embed] https://example.com/wiki\n\n[media: clip] video.mp4\n\n[image] missing.png\n"},
	{"![a|300](https://e.com/p.png)  <!--kvit align=left rounded shadow border-->",
		"<figure style=\"text-align:left\"><img alt=\"a\" src=\"https://e.com/p.png\" width=\"300\" class=\"bordered\" style=\"border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,0.25)\"></figure>",
		"[image: a] https://e.com/p.png\n"},
	{"centred  <!--kvit align=center-->\n\n# Title  <!--kvit align=right-->\n\nOnce upon  <!--kvit dropcap=3-->\n\n**Bold** open  <!--kvit dropcap=2 dropcapcolor=red dropcapfont=Georgia-->",
		"<p style=\"text-align:center\">centred</p><h1 id=\"title\" style=\"text-align:right\">Title</h1><p><span class=\"dropcap\" style=\"font-size:3.45em\">O</span>nce upon</p><p><strong><span class=\"dropcap\" style=\"font-size:2.30em;color:red;font-family:'Georgia'\">B</span>old</strong> open</p>",
		"centred\n\n# Title\n\nOnce upon\n\nBold open\n"},
	{"H~2~O x^2^ ==mark== ++under++ ~~gone~~ ***both*** __b__ _i_ snake_case_x",
		"<p>H<sub>2</sub>O x<sup>2</sup> <mark>mark</mark> <u>under</u> <s>gone</s> <strong><em>both</em></strong> <strong>b</strong> <em>i</em> snake_case_x</p>",
		"H2O x2 mark under gone both b i snake_case_x\n"},
	{"<span style=\"color:#c1121f\">red **b**</span> and <span style='color: blue'>b</span> <span style=\"color:x;y\">no</span>",
		"<p><span style=\"color:#c1121f\">red <strong>b</strong></span> and <span style=\"color:blue\">b</span> &lt;span style=&quot;color:x;y&quot;&gt;no&lt;/span&gt;</p>",
		"red b and b <span style=\"color:x;y\">no</span>\n"},
	{"[[Note]] [[Note|alias]] [[Note#Head]] [[#local]] see https://example.com/a. and (http://x.org/y)",
		"<p>Note alias Note#Head #local see <a href=\"https://example.com/a\">https://example.com/a</a>. and (<a href=\"http://x.org/y\">http://x.org/y</a>)</p>",
		"Note alias Note#Head #local see https://example.com/a. and (http://x.org/y)\n"},
	{"`code` ``tick ` in`` ```three``` \\`not`",
		"<p><code>code</code> <code>tick ` in</code> <code>three</code> `not`</p>",
		"code tick ` in three `not`\n"},
	{"1. one\n   1. sub one\n   2. sub two\n2. two\n- bullet\n  - nested\n    - deeper\n- [ ] todo\n  1. num under todo",
		"<ol><li>one<ol><li>sub one</li><li>sub two</li></ol></li><li>two</li></ol><ul><li>bullet<ul><li>nested<ul><li>deeper</li></ul></li></ul></li><li>&#9744; todo</li></ul><ol><ol><li>num under todo</li></ol></li></ol>",
		"1. one\n\n  1. sub one\n\n  2. sub two\n\n2. two\n\n- bullet\n\n  - nested\n\n    - deeper\n\n[ ] todo\n\n  1. num under todo\n"},
	{"   \n\n",
		"",
		""},
	{"Line with trailing tag <!--kvit x-->",
		"<p>Line with trailing tag</p>",
		"Line with trailing tag\n"},
	{"Para one\n![img](https://e.com/a.png)\nPara two",
		"<p>Para one</p><figure><img alt=\"img\" src=\"https://e.com/a.png\"></figure><p>Para two</p>",
		"Para one\n\n[image: img] https://e.com/a.png\n\nPara two\n"},
	{"- a\n\n- b\n\n\n- c",
		"<ul><li>a</li><li>b</li><li>c</li></ul>",
		"- a\n\n- b\n\n- c\n"},
	{"# A4: narrowing the QML surface\n\nWritten to be read cold: what the work was, what it produced, and what rests\non execution versus inspection. It is the record of architecture finding A4's\nQML half, done across 30 commits and merged as one.\n\n## What the finding asked\n\n`AppContext` published 44 string-named context properties. QML resolves such a\nname at runtime, so a misspelled or removed one yielded `undefined` and a subtly\nwrong render, invisible to any static tool. The finding asked that such a\nreference become a static error qmllint catches. \"Done\" is the two categories\nthat catch it — `unqualified` (a name resolving to nothing) and\n`missing-property` (a name resolving to the wrong thing) — enabled and failing\nthe gate across the whole `qml/` tree.\n\nThey are, over all 51 files. The baseline with them enabled was 2,587 + 670\nfindings; now zero, with three line-scoped suppressions, each a gap in Qt's own\ntype description (`Qt.application.screens`, `Qt.application.font`,\n`Text.positionAt`), none for first-party code.\n\n## What replaced the 44 context properties\n\n**Typed module singletons.** Every service is registered in a generated `Kvit`\nQML module and reached as `Theme.accent`, `NoteCollection.isOpen`, and so on.\nqmltyperegistrar writes the module's type description from `QML_ELEMENT` macros,\nso the description carries the real property surface and cannot drift from the\nC++ — it replaced a hand-written stub that listed type names and no members.\nRegistration is per-QML-engine through a `create()` factory reading a service\ntable the composing `AppContext` hangs on the engine, which preserves the\ndeliberately multi-instance composition that tests rely on.\n\nOne Qt trap is worth recording because it fails silently: `QQmlPrivate::`\n`singletonConstructionMode()` tests `std::is_default_constructible<T>` before it\nlooks for a `create()` factory. Every service takes `QObject *parent = nullptr`,\nso putting `QML_SINGLETON` on the class itself gets the factory ignored and Qt\ndefault-constructs an instance wired to nothing — no warning, no null, a valid\nobject bound to a service that does not exist. The registrations live in\n`src/qml/qmlsingletons.h` as `QML_FOREIGN` wrappers, whose branch Qt tests first.\n\n**Three declared QML types at the window/delegate boundary.** `BlockDelegateBase`\nis the interface every block delegate already implemented by convention;\n`main.qml` casts `itemAtIndex(i) as BlockDelegateBase` to call into a row.\n`KvitShell` is the window as a delegate sees it — the drag state, the\nlast-focused block, the editor modes — reached through `Window.window as\nKvitShell`. `BlockDragState` is the drag interface, declared as a type but\nimplemented in `main.qml`, because its body drives that window's own view\nobjects and could not move without dragging four of them with it.\n\n**`AppActions`.** The 20 commands a delegate sends up to the window (open a menu,\ninsert an image, scroll to a block) go through one typed singleton of named\nsignals; `main.qml` connects each to the function that already implemented it.\nAn unconnected signal is a no-op, which is exactly what the old\n`if (win && win.x)` probe achieved, so behaviour is preserved by construction.\n\n## The three defects the static gate caught, none of which the runtime gate could\n\nThese are the argument for the scope, and they are defects rather than lint\nnoise.\n\n**1. `DocumentStats.DocumentStats()` — the statistics panel, dead.**\n`DocumentStats` has a method also named `documentStats`; a rename hit both the\nobject and the method, producing a call to a member that does not exist. The\npanel threw on every recompute and showed nothing. It sat green through four\ncommits, because `ShellTests` loads the shell but never opens that panel, so\n`recompute()` never ran.\n\n**2. `editorEngine.stripFormatting` — Ctrl+Shift+V pasted nothing.**\n`editorEngine` is an id inside `EditableBlock.qml`; `main.qml` referenced it\nacross the file boundary, where ids do not reach. Paste-as-plain-text over a\nblock selection threw `ReferenceError` every time. Never executed at load, so\nnever seen.\n\n**3. A 66-site `ReferenceError`, introduced during this work.** The shell-handle\nrollout hardcoded `root` as the delegate root id; four delegates root at\n`delegate`, so 66 reads referenced an id absent in them. Every one would have\nthrown on first use, on drag, device-pixel-ratio and menu paths that do not run\nwhile the shell loads.\n\nAll three are `missing-property` or `unqualified` findings — the categories that\nwere disabled. A warning gate observes only code that executes; a linter reads\ncode whether it runs or not. That difference is the whole case, demonstrated on\nreal defects, twice on ones that would have shipped.\n\n## The cast, verified by experiment rather than cited\n\nThe 262 of 282 `Window.window` member accesses that were state reads, not\ncommands, could not be signalled away. The fix — `Window.window as KvitShell` —\nhad no prior art anyone could find, so it is not presented as known practice.\nThree probes established it on this Qt (6.10.1): the property-handle form lints\nclean; an uncast read still reports `missing-property`, so the check is not\nsilenced; and the handle resolves at runtime from inside a nested `ListView`\ndelegate two levels deep, returning the value. It rests on those three results\nrather than on established practice. A null cast yields null, so where a null\nguard existed it stayed: the cast makes the read typed without making the window\nguaranteed to be there.\n\n## The menu boundary, and the union that was avoided\n\nThe delegates query menu state (is this block's menu open) and then drive the\nreturned menu. The tempting move is one `CommandMenu` base type the three menus\nimplement — and it would have been wrong, because they do not share an\ninterface: `BlockMenu` has `targetIndex` and no `targets()`, the other two the\nreverse. A base type declaring both would type `BlockMenu` as something with\n`targets()`, and a call to it would lint clean and be `undefined` at runtime —\nthe exact `missing-property` failure this work enables the gate to catch.\n\nNo such type was built. `KvitShell` declares `activeBlockMenu(index)`,\n`activeMathMenu(host)`, `activeWikiMenu(host)`, `contextMenuHoldsSelection` and\n`openLink`; `main.qml` overrides each and reads the divergent members on the\nconcrete menu that has them. The delegate receives the menu as an untyped `var`\nand drives it, holding an opaque handle rather than a typed menu that could lie.\nQueries return through `KvitShell`, commands go out through `AppActions`, and the\ndelegate never names a menu. Mutating the block-menu override to call\n`targets()` fails the gate (exit 255), because `blockMenu` is typed as the\nconcrete `BlockMenu`. There is no shared type to over-promise.\n\n## Two hand-rolled workarounds that vanished\n\n`EditableBlock` and two siblings carried `appTheme` aliases because a bare\n`theme` inside the engine object resolved to the engine's own property; a\nsingleton cannot be shadowed by an object property, so the aliases went.\n`BacklinksPanel` carried an `entryData` alias because a nested Repeater's\n`modelData` shadowed the outer one; binding the scopes removed the shadowing and\nthe alias. Both fell out of the work rather than being sought — complexity\nleaving the tree rather than moving within it, which a refactor of this size\nusually cannot claim.\n\n## What rests on execution versus inspection\n\nMost of the conversion is verified by execution: `ShellTests` fails on any QML\nwarning at load and passed throughout, and 67 unit tests plus `QrcSyncGuard` are\ngreen from a clean build. Two areas rest on inspection, and should be read as\nsuch:\n\n- **The drag state — 132 of the reads.** `blockDrag` drives block\n  drag-and-drop, whose tests live in the Qt Quick integration suite, which does\n  not run in this environment (it fails heavily under WSLg regardless of the\n  code). qmllint proves the members resolve; `ShellTests` proves the shell\n  loads; neither proves a drag still works. Each site is `win.` becoming\n  `shell.` with no restructuring, which is what keeps it reviewable by eye.\n- **`TagStrip.chipFor()`** now finds its chip by model index rather than reading\n  an untyped property off `itemAt()`. Provably the same answer, three lines, but\n  its only callers are in `tests/tst_integration.qml`, which this environment\n  cannot run.\n\n## One habit, stated plainly\n\nEight times during this work a rewrite matched more of the code than its author\nhad read. The pattern is always the same: a search-and-replace or a regular\nexpression written against what the code was assumed to look like, applied to\nfiles that did not all look that way.\n\n| Instance | What the rewrite hit that it should not have | Caught by |\n|---|---|---|\n| `documentStats` → `DocumentStats` | the invokable of the same name, not only the object | strict lint (later) |\n| colour-menu id | cross-wired onto the span-type menu above it | strict lint |\n| `root.selectRange` | a method that lives on `selectionKeyHandler`, not the root | strict lint |\n| `win` → `root.shell` | the word \"window\" inside 33 comments | build (unused-id) / reading the diff |\n| bare-method prefixing | the function *definitions*, producing `function delegate.x()` | build (syntax) |\n| 66-site id | `root` in four files whose root id is `delegate` | strict lint |\n| `TocBlock` id | `tocRow`, an id that does not exist in that file | build |\n| `root.defaultFontFamily` | a property invented before it was a function | build |\n\nEvery instance was caught, three by tests, one by the build failing to compile,\nfour by the linter, and none shipped. The value is not any single catch; it is\nthat the rate is high, and the deepest-scoped files, where a delegate nests\ncomponents four levels down and `modelData` means a different object at each, are\nwhere it bit hardest. Writing a rewrite is not the same as\nreading the code it rewrites, and the static gate this work enables is now one\nof the things that reads it.\n\n## A note for whoever counts this area next\n\nFour separate times a count here moved on closer reading: 13 files became 14 when\none was actually read, \"add a pragma\" became per-delegate role declarations\nacross 33 files, \"113 calls to 13 functions\" became 262 state reads, and 282\nmember accesses became 265 when a regex stopped double-counting call\nparentheses. The counts were unreliable until the shapes were understood, which\nis why every phase here was measured before it was scoped rather than estimated\nfrom the finding.\n",
		"<h1 id=\"a4-narrowing-the-qml-surface\">A4: narrowing the QML surface</h1><p>Written to be read cold: what the work was, what it produced, and what rests<br>on execution versus inspection. It is the record of architecture finding A4's<br>QML half, done across 30 commits and merged as one.</p><h2 id=\"what-the-finding-asked\">What the finding asked</h2><p><code>AppContext</code> published 44 string-named context properties. QML resolves such a<br>name at runtime, so a misspelled or removed one yielded <code>undefined</code> and a subtly<br>wrong render, invisible to any static tool. The finding asked that such a<br>reference become a static error qmllint catches. &quot;Done&quot; is the two categories<br>that catch it — <code>unqualified</code> (a name resolving to nothing) and<br><code>missing-property</code> (a name resolving to the wrong thing) — enabled and failing<br>the gate across the whole <code>qml/</code> tree.</p><p>They are, over all 51 files. The baseline with them enabled was 2,587 + 670<br>findings; now zero, with three line-scoped suppressions, each a gap in Qt's own<br>type description (<code>Qt.application.screens</code>, <code>Qt.application.font</code>,<br><code>Text.positionAt</code>), none for first-party code.</p><h2 id=\"what-replaced-the-44-context-properties\">What replaced the 44 context properties</h2><p><strong>Typed module singletons.</strong> Every service is registered in a generated <code>Kvit</code><br>QML module and reached as <code>Theme.accent</code>, <code>NoteCollection.isOpen</code>, and so on.<br>qmltyperegistrar writes the module's type description from <code>QML_ELEMENT</code> macros,<br>so the description carries the real property surface and cannot drift from the<br>C++ — it replaced a hand-written stub that listed type names and no members.<br>Registration is per-QML-engine through a <code>create()</code> factory reading a service<br>table the composing <code>AppContext</code> hangs on the engine, which preserves the<br>deliberately multi-instance composition that tests rely on.</p><p>One Qt trap is worth recording because it fails silently: <code>QQmlPrivate::</code><br><code>singletonConstructionMode()</code> tests <code>std::is_default_constructible&lt;T&gt;</code> before it<br>looks for a <code>create()</code> factory. Every service takes <code>QObject *parent = nullptr</code>,<br>so putting <code>QML_SINGLETON</code> on the class itself gets the factory ignored and Qt<br>default-constructs an instance wired to nothing — no warning, no null, a valid<br>object bound to a service that does not exist. The registrations live in<br><code>src/qml/qmlsingletons.h</code> as <code>QML_FOREIGN</code> wrappers, whose branch Qt tests first.</p><p><strong>Three declared QML types at the window/delegate boundary.</strong> <code>BlockDelegateBase</code><br>is the interface every block delegate already implemented by convention;<br><code>main.qml</code> casts <code>itemAtIndex(i) as BlockDelegateBase</code> to call into a row.<br><code>KvitShell</code> is the window as a delegate sees it — the drag state, the<br>last-focused block, the editor modes — reached through <code>Window.window as\nKvitShell</code>. <code>BlockDragState</code> is the drag interface, declared as a type but<br>implemented in <code>main.qml</code>, because its body drives that window's own view<br>objects and could not move without dragging four of them with it.</p><p><strong><code>AppActions</code>.</strong> The 20 commands a delegate sends up to the window (open a menu,<br>insert an image, scroll to a block) go through one typed singleton of named<br>signals; <code>main.qml</code> connects each to the function that already implemented it.<br>An unconnected signal is a no-op, which is exactly what the old<br><code>if (win &amp;&amp; win.x)</code> probe achieved, so behaviour is preserved by construction.</p><h2 id=\"the-three-defects-the-static-gate-caught-none-of-which-the-runtime-gate-could\">The three defects the static gate caught, none of which the runtime gate could</h2><p>These are the argument for the scope, and they are defects rather than lint<br>noise.</p><p><strong>1. <code>DocumentStats.DocumentStats()</code> — the statistics panel, dead.</strong><br><code>DocumentStats</code> has a method also named <code>documentStats</code>; a rename hit both the<br>object and the method, producing a call to a member that does not exist. The<br>panel threw on every recompute and showed nothing. It sat green through four<br>commits, because <code>ShellTests</code> loads the shell but never opens that panel, so<br><code>recompute()</code> never ran.</p><p><strong>2. <code>editorEngine.stripFormatting</code> — Ctrl+Shift+V pasted nothing.</strong><br><code>editorEngine</code> is an id inside <code>EditableBlock.qml</code>; <code>main.qml</code> referenced it<br>across the file boundary, where ids do not reach. Paste-as-plain-text over a<br>block selection threw <code>ReferenceError</code> every time. Never executed at load, so<br>never seen.</p><p><strong>3. A 66-site <code>ReferenceError</code>, introduced during this work.</strong> The shell-handle<br>rollout hardcoded <code>root</code> as the delegate root id; four delegates root at<br><code>delegate</code>, so 66 reads referenced an id absent in them. Every one would have<br>thrown on first use, on drag, device-pixel-ratio and menu paths that do not run<br>while the shell loads.</p><p>All three are <code>missing-property</code> or <code>unqualified</code> findings — the categories that<br>were disabled. A warning gate observes only code that executes; a linter reads<br>code whether it runs or not. That difference is the whole case, demonstrated on<br>real defects, twice on ones that would have shipped.</p><h2 id=\"the-cast-verified-by-experiment-rather-than-cited\">The cast, verified by experiment rather than cited</h2><p>The 262 of 282 <code>Window.window</code> member accesses that were state reads, not<br>commands, could not be signalled away. The fix — <code>Window.window as KvitShell</code> —<br>had no prior art anyone could find, so it is not presented as known practice.<br>Three probes established it on this Qt (6.10.1): the property-handle form lints<br>clean; an uncast read still reports <code>missing-property</code>, so the check is not<br>silenced; and the handle resolves at runtime from inside a nested <code>ListView</code><br>delegate two levels deep, returning the value. It rests on those three results<br>rather than on established practice. A null cast yields null, so where a null<br>guard existed it stayed: the cast makes the read typed without making the window<br>guaranteed to be there.</p><h2 id=\"the-menu-boundary-and-the-union-that-was-avoided\">The menu boundary, and the union that was avoided</h2><p>The delegates query menu state (is this block's menu open) and then drive the<br>returned menu. The tempting move is one <code>CommandMenu</code> base type the three menus<br>implement — and it would have been wrong, because they do not share an<br>interface: <code>BlockMenu</code> has <code>targetIndex</code> and no <code>targets()</code>, the other two the<br>reverse. A base type declaring both would type <code>BlockMenu</code> as something with<br><code>targets()</code>, and a call to it would lint clean and be <code>undefined</code> at runtime —<br>the exact <code>missing-property</code> failure this work enables the gate to catch.</p><p>No such type was built. <code>KvitShell</code> declares <code>activeBlockMenu(index)</code>,<br><code>activeMathMenu(host)</code>, <code>activeWikiMenu(host)</code>, <code>contextMenuHoldsSelection</code> and<br><code>openLink</code>; <code>main.qml</code> overrides each and reads the divergent members on the<br>concrete menu that has them. The delegate receives the menu as an untyped <code>var</code><br>and drives it, holding an opaque handle rather than a typed menu that could lie.<br>Queries return through <code>KvitShell</code>, commands go out through <code>AppActions</code>, and the<br>delegate never names a menu. Mutating the block-menu override to call<br><code>targets()</code> fails the gate (exit 255), because <code>blockMenu</code> is typed as the<br>concrete <code>BlockMenu</code>. There is no shared type to over-promise.</p><h2 id=\"two-hand-rolled-workarounds-that-vanished\">Two hand-rolled workarounds that vanished</h2><p><code>EditableBlock</code> and two siblings carried <code>appTheme</code> aliases because a bare<br><code>theme</code> inside the engine object resolved to the engine's own property; a<br>singleton cannot be shadowed by an object property, so the aliases went.<br><code>BacklinksPanel</code> carried an <code>entryData</code> alias because a nested Repeater's<br><code>modelData</code> shadowed the outer one; binding the scopes removed the shadowing and<br>the alias. Both fell out of the work rather than being sought — complexity<br>leaving the tree rather than moving within it, which a refactor of this size<br>usually cannot claim.</p><h2 id=\"what-rests-on-execution-versus-inspection\">What rests on execution versus inspection</h2><p>Most of the conversion is verified by execution: <code>ShellTests</code> fails on any QML<br>warning at load and passed throughout, and 67 unit tests plus <code>QrcSyncGuard</code> are<br>green from a clean build. Two areas rest on inspection, and should be read as<br>such:</p><ul><li><strong>The drag state — 132 of the reads.</strong> <code>blockDrag</code> drives block<br>drag-and-drop, whose tests live in the Qt Quick integration suite, which does<br>not run in this environment (it fails heavily under WSLg regardless of the<br>code). qmllint proves the members resolve; <code>ShellTests</code> proves the shell<br>loads; neither proves a drag still works. Each site is <code>win.</code> becoming<br><code>shell.</code> with no restructuring, which is what keeps it reviewable by eye.</li><li><strong><code>TagStrip.chipFor()</code></strong> now finds its chip by model index rather than reading<br>an untyped property off <code>itemAt()</code>. Provably the same answer, three lines, but<br>its only callers are in <code>tests/tst_integration.qml</code>, which this environment<br>cannot run.</li></ul><h2 id=\"one-habit-stated-plainly\">One habit, stated plainly</h2><p>Eight times during this work a rewrite matched more of the code than its author<br>had read. The pattern is always the same: a search-and-replace or a regular<br>expression written against what the code was assumed to look like, applied to<br>files that did not all look that way.</p><table><tr><th>Instance</th><th>What the rewrite hit that it should not have</th><th>Caught by</th></tr><tr><td><code>documentStats</code> → <code>DocumentStats</code></td><td>the invokable of the same name, not only the object</td><td>strict lint (later)</td></tr><tr><td>colour-menu id</td><td>cross-wired onto the span-type menu above it</td><td>strict lint</td></tr><tr><td><code>root.selectRange</code></td><td>a method that lives on <code>selectionKeyHandler</code>, not the root</td><td>strict lint</td></tr><tr><td><code>win</code> → <code>root.shell</code></td><td>the word &quot;window&quot; inside 33 comments</td><td>build (unused-id) / reading the diff</td></tr><tr><td>bare-method prefixing</td><td>the function <em>definitions</em>, producing <code>function delegate.x()</code></td><td>build (syntax)</td></tr><tr><td>66-site id</td><td><code>root</code> in four files whose root id is <code>delegate</code></td><td>strict lint</td></tr><tr><td><code>TocBlock</code> id</td><td><code>tocRow</code>, an id that does not exist in that file</td><td>build</td></tr><tr><td><code>root.defaultFontFamily</code></td><td>a property invented before it was a function</td><td>build</td></tr></table><p>Every instance was caught, three by tests, one by the build failing to compile,<br>four by the linter, and none shipped. The value is not any single catch; it is<br>that the rate is high, and the deepest-scoped files, where a delegate nests<br>components four levels down and <code>modelData</code> means a different object at each, are<br>where it bit hardest. Writing a rewrite is not the same as<br>reading the code it rewrites, and the static gate this work enables is now one<br>of the things that reads it.</p><h2 id=\"a-note-for-whoever-counts-this-area-next\">A note for whoever counts this area next</h2><p>Four separate times a count here moved on closer reading: 13 files became 14 when<br>one was actually read, &quot;add a pragma&quot; became per-delegate role declarations<br>across 33 files, &quot;113 calls to 13 functions&quot; became 262 state reads, and 282<br>member accesses became 265 when a regex stopped double-counting call<br>parentheses. The counts were unreliable until the shapes were understood, which<br>is why every phase here was measured before it was scoped rather than estimated<br>from the finding.</p>",
		"# A4: narrowing the QML surface\n\nWritten to be read cold: what the work was, what it produced, and what rests\non execution versus inspection. It is the record of architecture finding A4's\nQML half, done across 30 commits and merged as one.\n\n## What the finding asked\n\nAppContext published 44 string-named context properties. QML resolves such a\nname at runtime, so a misspelled or removed one yielded undefined and a subtly\nwrong render, invisible to any static tool. The finding asked that such a\nreference become a static error qmllint catches. \"Done\" is the two categories\nthat catch it — unqualified (a name resolving to nothing) and\nmissing-property (a name resolving to the wrong thing) — enabled and failing\nthe gate across the whole qml/ tree.\n\nThey are, over all 51 files. The baseline with them enabled was 2,587 + 670\nfindings; now zero, with three line-scoped suppressions, each a gap in Qt's own\ntype description (Qt.application.screens, Qt.application.font,\nText.positionAt), none for first-party code.\n\n## What replaced the 44 context properties\n\nTyped module singletons. Every service is registered in a generated Kvit\nQML module and reached as Theme.accent, NoteCollection.isOpen, and so on.\nqmltyperegistrar writes the module's type description from QML_ELEMENT macros,\nso the description carries the real property surface and cannot drift from the\nC++ — it replaced a hand-written stub that listed type names and no members.\nRegistration is per-QML-engine through a create() factory reading a service\ntable the composing AppContext hangs on the engine, which preserves the\ndeliberately multi-instance composition that tests rely on.\n\nOne Qt trap is worth recording because it fails silently: QQmlPrivate::\nsingletonConstructionMode() tests std::is_default_constructible<T> before it\nlooks for a create() factory. Every service takes QObject *parent = nullptr,\nso putting QML_SINGLETON on the class itself gets the factory ignored and Qt\ndefault-constructs an instance wired to nothing — no warning, no null, a valid\nobject bound to a service that does not exist. The registrations live in\nsrc/qml/qmlsingletons.h as QML_FOREIGN wrappers, whose branch Qt tests first.\n\nThree declared QML types at the window/delegate boundary. BlockDelegateBase\nis the interface every block delegate already implemented by convention;\nmain.qml casts itemAtIndex(i) as BlockDelegateBase to call into a row.\nKvitShell is the window as a delegate sees it — the drag state, the\nlast-focused block, the editor modes — reached through Window.window as\nKvitShell. BlockDragState is the drag interface, declared as a type but\nimplemented in main.qml, because its body drives that window's own view\nobjects and could not move without dragging four of them with it.\n\nAppActions. The 20 commands a delegate sends up to the window (open a menu,\ninsert an image, scroll to a block) go through one typed singleton of named\nsignals; main.qml connects each to the function that already implemented it.\nAn unconnected signal is a no-op, which is exactly what the old\nif (win && win.x) probe achieved, so behaviour is preserved by construction.\n\n## The three defects the static gate caught, none of which the runtime gate could\n\nThese are the argument for the scope, and they are defects rather than lint\nnoise.\n\n1. DocumentStats.DocumentStats() — the statistics panel, dead.\nDocumentStats has a method also named documentStats; a rename hit both the\nobject and the method, producing a call to a member that does not exist. The\npanel threw on every recompute and showed nothing. It sat green through four\ncommits, because ShellTests loads the shell but never opens that panel, so\nrecompute() never ran.\n\n2. editorEngine.stripFormatting — Ctrl+Shift+V pasted nothing.\neditorEngine is an id inside EditableBlock.qml; main.qml referenced it\nacross the file boundary, where ids do not reach. Paste-as-plain-text over a\nblock selection threw ReferenceError every time. Never executed at load, so\nnever seen.\n\n3. A 66-site ReferenceError, introduced during this work. The shell-handle\nrollout hardcoded root as the delegate root id; four delegates root at\ndelegate, so 66 reads referenced an id absent in them. Every one would have\nthrown on first use, on drag, device-pixel-ratio and menu paths that do not run\nwhile the shell loads.\n\nAll three are missing-property or unqualified findings — the categories that\nwere disabled. A warning gate observes only code that executes; a linter reads\ncode whether it runs or not. That difference is the whole case, demonstrated on\nreal defects, twice on ones that would have shipped.\n\n## The cast, verified by experiment rather than cited\n\nThe 262 of 282 Window.window member accesses that were state reads, not\ncommands, could not be signalled away. The fix — Window.window as KvitShell —\nhad no prior art anyone could find, so it is not presented as known practice.\nThree probes established it on this Qt (6.10.1): the property-handle form lints\nclean; an uncast read still reports missing-property, so the check is not\nsilenced; and the handle resolves at runtime from inside a nested ListView\ndelegate two levels deep, returning the value. It rests on those three results\nrather than on established practice. A null cast yields null, so where a null\nguard existed it stayed: the cast makes the read typed without making the window\nguaranteed to be there.\n\n## The menu boundary, and the union that was avoided\n\nThe delegates query menu state (is this block's menu open) and then drive the\nreturned menu. The tempting move is one CommandMenu base type the three menus\nimplement — and it would have been wrong, because they do not share an\ninterface: BlockMenu has targetIndex and no targets(), the other two the\nreverse. A base type declaring both would type BlockMenu as something with\ntargets(), and a call to it would lint clean and be undefined at runtime —\nthe exact missing-property failure this work enables the gate to catch.\n\nNo such type was built. KvitShell declares activeBlockMenu(index),\nactiveMathMenu(host), activeWikiMenu(host), contextMenuHoldsSelection and\nopenLink; main.qml overrides each and reads the divergent members on the\nconcrete menu that has them. The delegate receives the menu as an untyped var\nand drives it, holding an opaque handle rather than a typed menu that could lie.\nQueries return through KvitShell, commands go out through AppActions, and the\ndelegate never names a menu. Mutating the block-menu override to call\ntargets() fails the gate (exit 255), because blockMenu is typed as the\nconcrete BlockMenu. There is no shared type to over-promise.\n\n## Two hand-rolled workarounds that vanished\n\nEditableBlock and two siblings carried appTheme aliases because a bare\ntheme inside the engine object resolved to the engine's own property; a\nsingleton cannot be shadowed by an object property, so the aliases went.\nBacklinksPanel carried an entryData alias because a nested Repeater's\nmodelData shadowed the outer one; binding the scopes removed the shadowing and\nthe alias. Both fell out of the work rather than being sought — complexity\nleaving the tree rather than moving within it, which a refactor of this size\nusually cannot claim.\n\n## What rests on execution versus inspection\n\nMost of the conversion is verified by execution: ShellTests fails on any QML\nwarning at load and passed throughout, and 67 unit tests plus QrcSyncGuard are\ngreen from a clean build. Two areas rest on inspection, and should be read as\nsuch:\n\n- The drag state — 132 of the reads. blockDrag drives block\ndrag-and-drop, whose tests live in the Qt Quick integration suite, which does\nnot run in this environment (it fails heavily under WSLg regardless of the\ncode). qmllint proves the members resolve; ShellTests proves the shell\nloads; neither proves a drag still works. Each site is win. becoming\nshell. with no restructuring, which is what keeps it reviewable by eye.\n\n- TagStrip.chipFor() now finds its chip by model index rather than reading\nan untyped property off itemAt(). Provably the same answer, three lines, but\nits only callers are in tests/tst_integration.qml, which this environment\ncannot run.\n\n## One habit, stated plainly\n\nEight times during this work a rewrite matched more of the code than its author\nhad read. The pattern is always the same: a search-and-replace or a regular\nexpression written against what the code was assumed to look like, applied to\nfiles that did not all look that way.\n\nInstance                      | What the rewrite hit that it should not have              | Caught by\n------------------------------+-----------------------------------------------------------+-------------------------------------\ndocumentStats → DocumentStats | the invokable of the same name, not only the object       | strict lint (later)\ncolour-menu id                | cross-wired onto the span-type menu above it              | strict lint\nroot.selectRange              | a method that lives on selectionKeyHandler, not the root  | strict lint\nwin → root.shell              | the word \"window\" inside 33 comments                      | build (unused-id) / reading the diff\nbare-method prefixing         | the function definitions, producing function delegate.x() | build (syntax)\n66-site id                    | root in four files whose root id is delegate              | strict lint\nTocBlock id                   | tocRow, an id that does not exist in that file            | build\nroot.defaultFontFamily        | a property invented before it was a function              | build\n\nEvery instance was caught, three by tests, one by the build failing to compile,\nfour by the linter, and none shipped. The value is not any single catch; it is\nthat the rate is high, and the deepest-scoped files, where a delegate nests\ncomponents four levels down and modelData means a different object at each, are\nwhere it bit hardest. Writing a rewrite is not the same as\nreading the code it rewrites, and the static gate this work enables is now one\nof the things that reads it.\n\n## A note for whoever counts this area next\n\nFour separate times a count here moved on closer reading: 13 files became 14 when\none was actually read, \"add a pragma\" became per-delegate role declarations\nacross 33 files, \"113 calls to 13 functions\" became 262 state reads, and 282\nmember accesses became 265 when a regex stopped double-counting call\nparentheses. The counts were unreliable until the shapes were understood, which\nis why every phase here was measured before it was scoped rather than estimated\nfrom the finding.\n"},
}

func TestExportMatchesQt(t *testing.T) {
	for _, c := range qtExports {
		html := HTMLFromMarkdown(c.md, "T", Options{})
		body := html[strings.Index(html, "<body>\n")+7 : strings.LastIndex(html, "\n</body>")]
		if body != c.body {
			t.Errorf("%q:\n got %q\nwant %q", c.md, body, c.body)
		}
		if text := TextFromMarkdown(c.md, Options{}); text != c.text {
			t.Errorf("%q as text:\n got %q\nwant %q", c.md, text, c.text)
		}
	}
}

// qtConversions are HTML inputs with the Markdown the converter makes of
// each: clipboard payloads from a browser, a word processor and a document
// editor, and HTML that a browser would read differently.
var qtConversions = []struct{ html, md string }{
	{"<h1>Title</h1><h2>Section</h2><h6>Deep</h6>",
		"# Title\n\n## Section\n\n###### Deep"},
	{"<p><b>bold</b> <strong>s</strong> <i>it</i> <em>e</em> <s>gone</s> <del>d</del> <u>u</u></p>",
		"**bold** **s** *it* *e* ~~gone~~ d u"},
	{"<p>a <b>b</b> c</p><p>run <code>ls -l</code> now</p><pre>int main() {}</pre>",
		"a **b** c\n\nrun `ls -l` now\n\n```\nint main() {}\n```"},
	{"<p><a href=\"https://example.com\">site</a> <a href=\"https://e.com\"><b>bold link</b></a> <a name=\"x\">anchor</a></p>",
		"[site](https://example.com) [**bold link**](https://e.com) anchor"},
	{"<ul><li>one</li><li>two</li></ul><ol><li>one</li><li>two</li></ol>",
		"- one\n\n- two\n\n1. one\n\n2. two"},
	{"<ul><li>outer</li><ul><li>inner</li></ul></ul>",
		"- outer\n\n  - inner"},
	{"<ol><li>a</li><li>b<ol><li>x</li><li>y</li></ol></li><li>c</li></ol>",
		"1. a\n\n2. b\n\n  1. x\n\n  2. y\n\n3. c"},
	{"<blockquote>quoted</blockquote><blockquote><p>a</p><p>b</p></blockquote>",
		"> quoted\n\n> a\n\n> b"},
	{"<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>",
		"| A | B |\n| --- | --- |\n| 1 | 2 |"},
	{"<table><thead><tr><th>A</th><th><b>B</b></th></tr></thead><tbody><tr><td><b>1</b></td><td>a|b</td></tr><tr><td colspan=\"2\">wide</td></tr></tbody></table>",
		"| A | B |\n| --- | --- |\n| **1** | a\\|b |\n| wide | wide |"},
	{"<p>one</p><p></p><p></p><p>two</p>",
		"one\n\ntwo"},
	{"<p>a &amp; b &lt; c &nbsp;d &eacute; &#233; &#x41;</p>",
		"a & b < c \u00a0d é é A"},
	{"just text",
		"just text"},
	{"<p>2 * 3 * 4</p><p>a_b_c</p><p>[x]</p><p>`t`</p>",
		"2 \\* 3 \\* 4\n\na\\_b\\_c\n\n\\[x\\]\n\n\\`t\\`"},
	{"<p># literal heading</p><p>#tag</p><p>- literal</p><p>+ literal</p><p>&gt; not</p><p>---</p><p>| a | b |</p>",
		"\\# literal heading\n\n\\#tag\n\n\\- literal\n\n\\+ literal\n\n\\> not\n\n\\---\n\n\\| a | b |"},
	{"<ul><li># literal</li></ul><blockquote># literal</blockquote><p>issue #42</p>",
		"- \\# literal\n\n> \\# literal\n\nissue #42"},
	{"<p>before<img src=\"http://h/pic.png\">after</p><p><img src=\"a b(c).png\"></p><p><img src=\"pic.png\"></p>",
		"before![](http://h/pic.png)after\n\n![](a%20b%28c%29.png)\n\n![](pic.png)"},
	{"<pre>┌──────────┐\n│ Editor   │\n│ (QML)    │\n└────┬─────┘</pre>",
		"```\n┌──────────┐\n│ Editor   │\n│ (QML)    │\n└────┬─────┘\n```"},
	{"<pre>one\n\nthree</pre>",
		"```\none\n\nthree\n```"},
	{"<pre>plain\n``` inside</pre>",
		"````\nplain\n``` inside\n````"},
	{"<p>before</p><pre>a\nb</pre><p>after</p>",
		"before\n\n```\na\nb\n```\n\nafter"},
	{"<pre style=\"font-family: Arial\">a\nb</pre>",
		"```\na\nb\n```"},
	{"<p><code>inline_code_run</code></p>",
		"```\ninline_code_run\n```"},
	{"<p>run <code>a ` b</code> now</p><p>run <code>``</code> now</p><p>run <code>`x</code> now</p>",
		"run ``a ` b`` now\n\nrun ``` `` ``` now\n\nrun `` `x `` now"},
	{"<pre>a ``` b</pre>",
		"````\na ``` b\n````"},
	{"<p><a href=\"http://x/a_(b)_c\">wiki</a></p>",
		"[wiki](http://x/a_%28b%29_c)"},
	{"<p>a<br>b</p><p>c<br/>\nd</p>",
		"a\u2028b\n\nc\u2028d"},
	{"<ul>\n  <li>one</li>\n  <li>two</li>\n</ul>",
		"- one\n\n- two"},
	{"<li><p>para</p></li>",
		"para"},
	{"<p>x</p><hr><p>y</p>",
		"x\n\ny"},
	{"<p><b>a</b><b>b</b></p>",
		"**ab**"},
	{"<p><span style=\"font-weight:bold\">w</span> <span style=\"font-style:italic\">i</span> <span style=\"text-decoration: line-through\">s</span> <span style=\"font-weight:600\">semi</span> <span style=\"font-family: 'Courier New'\">mono</span></p>",
		"**w** *i* ~~s~~ semi `mono`"},
	{"<html><head><title>T</title><style>p{}</style></head><body><p>x</p><script>y()</script></body></html>",
		"x"},
	{"<p>one<p>two",
		"one\n\ntwo"},
	{"<pre>\nfirst</pre>",
		"```\nfirst\n```"},
	{"<p style=\"margin-left:40px;margin-right:40px\">indented</p><p style=\"margin-left:40px\">left only</p>",
		"> indented\n\nleft only"},
	{"<section>a</section><section>b</section><div>c</div><div>d</div>",
		"ab\n\nc\n\nd"},
	{"<div><p>x</p></div><div>text <p>inner</p> tail</div>",
		"x\n\ntext\n\ninner\n\ntail"},
	{"<!--StartFragment--><meta charset='utf-8'><span style=\"color: rgb(0,0,0);\">Copied <b>text</b></span><!--EndFragment-->",
		"Copied **text**"},
	{"<p>   leading and   inner   spaces   </p>",
		"leading and inner spaces"},
	{"<ol type=\"a\"><li>x</li></ol><ul type=\"1\"><li>y</li></ul>",
		"1. x\n\n1. y"},
	{"<dl><dt>term</dt><dd>definition</dd></dl>",
		"term\n\ndefinition"},
	{"<p><i><b>both</b></i> <a href=\"u\"><code>c</code></a></p>",
		"***both*** [`c`](u)"},
	{"<table><tr><td>a<table><tr><td>nested</td></tr></table></td><td>b</td></tr></table>",
		"| a | b |\n| --- | --- |"},
	{"<p>a</p>\n\n<pre><code>x = 1\ny = 2\n</code></pre>\n<p>b</p>",
		"a\n\n```\nx = 1\ny = 2\n```\n\nb"},
	{"<blockquote><ul><li>in quote</li></ul></blockquote>",
		"- in quote"},
	{"<h2><a href=\"#x\">Linked</a> heading</h2>",
		"## [Linked](#x) heading"},
	{"<p>tab\tsep</p><p>nb&nbsp;&nbsp;sp</p>",
		"tab sep\n\nnb\u00a0\u00a0sp"},
	{"<p style=\"white-space:nowrap\">nowrap text</p>",
		"```\nnowrap\u00a0text\n```"},
	{"<p>a <del>x</del> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <strike>x</strike> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <s>x</s> b</p><p>c</p>",
		"a ~~x~~ b\n\nc"},
	{"<p>a <ins>x</ins> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <cite>x</cite> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <var>x</var> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <dfn>x</dfn> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <kbd>x</kbd> b</p><p>c</p>",
		"a `x` b\n\nc"},
	{"<p>a <samp>x</samp> b</p><p>c</p>",
		"a `x` b\n\nc"},
	{"<p>a <tt>x</tt> b</p><p>c</p>",
		"a `x` b\n\nc"},
	{"<p>a <code>x</code> b</p><p>c</p>",
		"a `x` b\n\nc"},
	{"<p>a <address>x</address> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <big>x</big> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <small>x</small> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <nobr>x</nobr> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <section>x</section> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <article>x</article> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <span>x</span> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <font>x</font> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <em>x</em> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <i>x</i> b</p><p>c</p>",
		"a *x* b\n\nc"},
	{"<p>a <b>x</b> b</p><p>c</p>",
		"a **x** b\n\nc"},
	{"<p>a <strong>x</strong> b</p><p>c</p>",
		"a **x** b\n\nc"},
	{"<p>a <u>x</u> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <sub>x</sub> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <sup>x</sup> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <q>x</q> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <abbr>x</abbr> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <mark>x</mark> b</p><p>c</p>",
		"a x b\n\nc"},
	{"<p>a <div>x y</div> b</p>",
		"a\n\nx y b"},
	{"<p>a <address>x y</address> b</p>",
		"a *x y* b"},
	{"<p>a <center>x y</center> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <blockquote>x y</blockquote> b</p>",
		"a\n\n> x y\n\nb"},
	{"<p>a <dl>x y</dl> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <dt>x y</dt> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <dd>x y</dd> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <pre>x y</pre> b</p>",
		"a\n\n```\nx y\n```\n\nb"},
	{"<p>a <h1>x y</h1> b</p>",
		"a\n\n# x y\n\nb"},
	{"<p>a <p>x y</p> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <li>x y</li> b</p>",
		"a\n\nx y\n\nb"},
	{"<p>a <ul>x y</ul> b</p>",
		"a\n\n> x y\n\nb"},
	{"<p>a <ol>x y</ol> b</p>",
		"a\n\n> x y\n\nb"},
	{"<p>a <hr>x y</hr> b</p>",
		"a\n\nx y b"},
	{"<p>a <section>x y</section> b</p>",
		"a x y b"},
	{"<p>a <nobr>x y</nobr> b</p>",
		"a x\u00a0y b"},
	{"<div>a<div>b</div>c</div>",
		"a\n\nbc"},
	{"<ul><li>a<li>b</ul>",
		"- a\n\n- b"},
	{"<table><tr><td>a<td>b<tr><td>c</table>",
		"| a | b |\n| --- | --- |\n| c |  |"},
	{"<p><nobr>x y</nobr> z</p>",
		"x\u00a0y z"},
	{"<dl><dt>t</dt><dd>d</dd></dl>",
		"t\n\nd"},
	{"text<blockquote>q</blockquote>after",
		"text\n\n> q\n\nafter"},
	{"<blockquote>a<blockquote>b</blockquote></blockquote>",
		"> a\n\n> b"},
	{"<ul><li>a<p>b</p>c</li></ul>",
		"- a\n\n> b\n\n> c"},
	{"<ol><li></li><li>b</li></ol>",
		"1. b"},
	{"<ol start=\"3\"><li>a</li></ol>",
		"1. a"},
	{"<ul><li>a<ul><li>b</li></ul>c</li></ul>",
		"- a\n\n  - b\n\n> c"},
	{"<table><tr><th>A</th></tr><tr><th>B</th></tr></table>",
		"| A |\n| --- |\n| **B** |"},
	{"<p>a<br> b</p>",
		"a\u2028b"},
	{"<h1>a<br>b</h1>",
		"# a\u2028b"},
	{"<table><caption>Cap</caption><tr><td>a</td></tr></table>",
		"Cap\n\n| a |\n| --- |"},
	{"<table><tr><td rowspan=\"2\">r</td><td>a</td></tr><tr><td>b</td></tr></table>",
		"| r | a |\n| --- | --- |\n| r | b |"},
	{"<pre><b>bold</b> code</pre>",
		"```\nbold code\n```"},
	{"<p>x <code>a  b</code> y</p>",
		"x `a b` y"},
	{"<blockquote><h2>H</h2></blockquote>",
		"## H"},
	{"<ul><li><pre>c1\nc2</pre></li></ul>",
		"```\nc1\nc2\n```"},
	{"<div>a</div>b",
		"ab"},
	{"<div><p>x</p></div>y",
		"x\n\ny"},
	{"<div>a</div><div>b</div>",
		"a\n\nb"},
	{"<div></div>x",
		"x"},
	{"<p>a</p><p></p><pre>x</pre><p></p><pre>y</pre>",
		"a\n\n```\nx\ny\n```"},
	{"<ol><li>a</li><li></li><li>b</li></ol>",
		"1. a\n\n2. b"},
	{"<pre>x</pre><pre>y</pre>",
		"```\nx\ny\n```"},
	{"<pre>x</pre><div></div><pre>y</pre>",
		"```\nx\ny\n```"},
	{"<p>a</p>b",
		"a\n\nb"},
	{"<blockquote>a</blockquote>b",
		"> a\n\nb"},
	{"<h1>a</h1>b",
		"# a\n\nb"},
	{"<div>a<p>b</p>c</div>",
		"a\n\nb\n\nc"},
	{"<center>a</center>b",
		"a\n\nb"},
	{"<pre>x</pre>b",
		"```\nx\n```\n\nb"},
	{"<div><div>a</div></div>b",
		"a\n\nb"},
	{"<ol><li><p>a</p></li><li>b</li></ol>",
		"1. a\n\n2. b"},
	{"<ol><li>a<br></li><li> </li><li>b</li></ol>",
		"1. a\n\n2. b"},
	{"<span style=\"white-space:pre\">a  b</span> c",
		"a  b c"},
	{"<div style=\"white-space:pre\">a  b\\nc</div>",
		"```\na  b\\nc\n```"},
	{"<p>x</p><table><tr><td>a</td></tr></table><p>y</p>",
		"x\n\n| a |\n| --- |\n\ny"},
	{"<pre>a</pre>\\n<pre>b</pre>",
		"```\na\n```\n\n\\\\n\n\n```\nb\n```"},
	{"<ul><li>x</li></ul>y",
		"- x\n\ny"},
	{"<table><tr><td><p>a</p><p>b</p></td></tr></table>",
		"| a b |\n| --- |"},
	{"<div>a</div><p>b</p>",
		"a\n\nb"},
	{"<p>a</p><div>b</div>c",
		"a\n\nbc"},
	{"<style>body{margin:24px auto}</style><p>x</p>",
		"x"},
	{"<style>body{padding:0 16px}</style><p>x</p>",
		"x"},
	{"<style>p{margin:0 10px}</style><p>x</p>",
		"> x"},
	{"<style>.t{font-weight:bold}</style><div class=\"t\">x</div>",
		"**x**"},
	{"<style>.a .t{font-weight:bold}</style><div class=\"a\"><div class=\"t\">x</div></div><div class=\"t\">y</div>",
		"**x**\n\ny"},
	{"<style>blockquote{margin:0}</style><blockquote>x</blockquote>",
		"x"},
	{"<style>body{max-width:760px}</style><p>x</p>",
		"x"},
	{"<body style=\"margin:24px auto\"><p>x</p></body>",
		"> x"},
	{"<p style=\"margin:24px auto\">x</p>",
		"> x"},
	{"<p style=\"margin:0 16px\">x</p>",
		"> x"},
	{"<p style=\"padding:0 16px\">x</p>",
		"x"},
	{"<div style=\"margin-left:10px\"><p style=\"margin-right:10px\">x</p></div>",
		"> x"},
	{"<style>p.c{font-style:italic}</style><p class=\"c\">x</p><p>y</p>",
		"*x*\n\ny"},
	{"<style>#i{font-weight:bold}</style><p id=\"i\">x</p>",
		"**x**"},
	{"<style>h1,h2{font-weight:normal}</style><h1>x</h1><p><b>y</b></p>",
		"# x\n\n**y**"},
	{"<style>code{font-family:Arial}</style><p><code>x</code> y</p>",
		"x y"},
	{"<style>span.m{font-family:monospace}</style><p><span class=\"m\">x</span> y</p>",
		"`x` y"},
	{"<style>b{font-weight:normal}</style><p><b>x</b></p>",
		"x"},
	{"<style>body{margin:24px}</style><p>x</p>",
		"x"},
	{"<style>div > .t{font-weight:bold}</style><div><span class=\"t\">x</span></div>",
		"**x**"},
	{"<style>p{white-space:pre}</style><p>a  b</p>",
		"```\na  b\n```"},
	{"<style>.x{text-decoration:line-through}</style><p><span class=\"x\">x</span> y</p>",
		"~~x~~ y"},
	{"<style>*{font-weight:bold}</style><p>x</p>",
		"**x**"},
	{"<style>@media print{p{font-weight:bold}}</style><p>x</p>",
		"x"},
	{"<p style=\"margin:0 auto\">x</p>",
		"> x"},
	{"<p style=\"margin-left:auto;margin-right:auto\">x</p>",
		"> x"},
	{"<p style=\"margin:10px 0\">x</p>",
		"x"},
	{"<p style=\"margin-left:0.5em;margin-right:1em\">x</p>",
		"> x"},
	{"<p style=\"margin-left:-5px;margin-right:10px\">x</p>",
		"x"},
	{"<style>p:hover{font-weight:bold}</style><p>x</p>",
		"x"},
	{"<style>p[title]{font-weight:bold}</style><p title=\"t\">x</p><p>y</p>",
		"**x**\n\ny"},
	{"<style>.t{font-weight:bold} p{font-weight:normal}</style><p class=\"t\">x</p>",
		"**x**"},
	{"<style>p{font-weight:bold !important}</style><p style=\"font-weight:normal\">x</p>",
		"x"},
	{"<style>p{font-weight:bold}</style><p style=\"font-weight:normal\">x</p>",
		"x"},
	{"<style>p{font-weight:bold} p{font-weight:normal}</style><p>x</p>",
		"x"},
	{"<style>/* c */ .a{font-style:italic}</style><p class=\"a b\">x</p>",
		"*x*"},
	{"<style>div p{margin-left:5px;margin-right:5px}</style><div><p>x</p></div><p>y</p>",
		"> x\n\ny"},
	{"<style>body{margin:24px auto}</style><body><p>x</p></body>",
		"> x"},
	{"<style>body{padding:0 16px}</style><body><p>x</p></body>",
		"x"},
	{"<style>ul{margin:0 20px}</style><ul><li>x</li></ul><p>y</p>",
		"- x\n\ny"},
	{"<p style=\"margin: 1px 2px 3px\">x</p>",
		"> x"},
	{"<p style=\"margin: 1px 0 3px 4px\">x</p>",
		"x"},
	{"<p style=\"margin-left:10px;margin-right:0\">x</p>",
		"x"},
	{"<blockquote style=\"margin-left:0\">x</blockquote>",
		"x"},
	{"<p style=\"margin:5%\">x</p>",
		"> x"},
	{"<style>P{font-weight:bold}</style><p>x</p>",
		"**x**"},
	{"<style>.A{font-weight:bold}</style><p class=\"a\">x</p>",
		"x"},
	{"<p style=\"-qt-block-indent:1\">x</p>",
		"> x"},
	{"<p style=\"text-indent:20px\">x</p>",
		"x"},
	{"<dd>x</dd><dd style=\"margin-right:5px\">y</dd>",
		"x\n\n> y"},
	{"<blockquote><p>a</p>b</blockquote>",
		"> a\n\nb"},
	{"<pre>x</pre>\n<pre>y</pre>",
		"```\nx\ny\n```"},
	{"<pre>x</pre> ",
		"```\nx \n```"},
	{"<pre>x</pre>\n<p>y</p>",
		"```\nx\n```\n\ny"},
	{"<body><pre>x</pre>\n</body>",
		"```\nx\n```"},
	{"<pre>x</pre>\n",
		"```\nx \n```"},
	{"<body style=\"margin:0 9px\">plain</body>",
		"> plain"},
	{"<body style=\"margin:0 9px\"><p>a</p>b</body>",
		"> a\n\nb"},
	{"<div style=\"margin:0 9px\">a<p>b</p>c</div>",
		"> a\n\n> b\n\nc"},
	{"<pre>x</pre><b> </b>",
		"```\nx \n```"},
	{"<pre>x</pre> <p>y</p>",
		"```\nx\n```\n\ny"},
	{"<p>a</p> ",
		"a"},
	{"<pre>x</pre>\n<pre>y</pre>\n",
		"```\nx\ny \n```"},
	{"<ul><li>a</li>\n</ul>\n<pre>x</pre>\n",
		"- a\n\n```\nx \n```"},
	{"<pre>x</pre>z",
		"```\nx\n```\n\nz"},
	{"<blockquote>a<br>b</blockquote>",
		"> a\u2028b"},
	{"<h1>a<div>b</div>c</h1>",
		"# a\n\n# bc"},
	{"<pre>x</pre>  <pre>y</pre>",
		"```\nx \ny\n```"},
	{"<pre>x</pre>\n\n<pre>y</pre>",
		"```\nx \ny\n```"},
	{"<p><code>x</code> </p><p>y</p>",
		"`x`\n\ny"},
	{"<p><code>x</code> </p>",
		"`x`"},
	{"<p><code>x</code></p> <p>y</p>",
		"```\nx\n```\n\ny"},
	{"<p><code>x</code></p>  <p>y</p>",
		"`x`\n\ny"},
	{"<pre>x</pre>\n\n",
		"```\nx \n```"},
	{"<p><code>x</code></p>\n\n",
		"`x`"},
	{"<div><pre>x</pre>\n\n</div>",
		"```\nx \n```"},
	{"<pre>x</pre><span>\n</span><pre>y</pre>",
		"```\nx \ny\n```"},
	{"<p><code>x</code>\n</p><p>y</p>",
		"`x`\n\ny"},
	{"<p>\n<code>x</code>\n</p>",
		"`x`"},
	{"<b>a</b> <pre>x</pre>",
		"**a**\n\n```\nx\n```"},
	{"<pre>x</pre> y",
		"```\nx\n```\n\ny"},
	{"<p>a</p><img src=\"x.png\">b",
		"a![](x.png)\n\nb"},
	{"<p>a</p><br>b",
		"a\n\nb"},
	{"<p>a</p><span>c</span>",
		"a\n\nc"},
	{"<p>a</p><b>c</b>d",
		"a\n\n**c**d"},
	{"<p>a</p>c<b>d</b>",
		"a\n\nc**d**"},
	{"<p>a</p><img src=\"x.png\"><p>b</p>",
		"a![](x.png)\n\nb"},
	{"<p></p><span>c</span>",
		"c"},
	{"<p></p>c",
		"c"},
	{"<b>x<span style=\"color:red\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"font-family:Arial\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<u>y</u>z</b>",
		"**x****y****z**"},
	{"<b>x<sub>y</sub>z</b>",
		"**x****y****z**"},
	{"<b>x<a name=\"n\">y</a>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"color:red\">y</span><span style=\"color:red\">z</span></b>",
		"**x****yz**"},
	{"<b>x<span style=\"background:yellow\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<small>y</small>z</b>",
		"**x****y****z**"},
	{"<b>x<mark>y</mark>z</b>",
		"**xyz**"},
	{"<b>x<span class=\"q\">y</span>z</b>",
		"**xyz**"},
	{"<b>x<span style=\"letter-spacing:2px\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<font color=\"red\">y</font>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"color:red\">y</span><font color=\"red\">z</font></b>",
		"**x****yz**"},
	{"<i>x<span style=\"text-decoration:underline\">y</span>z</i>",
		"*x**y**z*"},
	{"<b>x<span style=\"font-size:12pt\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"vertical-align:super\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"font-variant:small-caps\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"text-transform:uppercase\">y</span>z</b>",
		"**x****y****z**"},
	{"<b>x<span style=\"color:#ff0000\">y</span><span style=\"color:red\">z</span></b>",
		"**x****yz**"},
	{"<meta charset='utf-8'><h2 style=\"box-sizing: border-box; margin: 0px 0px 16px; font-weight: 600; font-size: 1.5em; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, sans-serif;\">Installation</h2><p style=\"box-sizing: border-box; margin: 0px 0px 16px; color: rgb(31, 35, 40); font-family: -apple-system, sans-serif; font-size: 16px;\">Run <code style=\"box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: rgba(129, 139, 152, 0.12); border-radius: 6px;\">go install ./...</code> and then <strong style=\"box-sizing: border-box; font-weight: 600;\">restart</strong> the <a href=\"https://example.com/docs\" style=\"box-sizing: border-box; color: rgb(9, 105, 218);\">service</a>.</p><ul style=\"box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-size: 16px;\"><li style=\"box-sizing: border-box;\">First <em>item</em></li><li style=\"box-sizing: border-box; margin-top: 0.25em;\">Second item<ul style=\"box-sizing: border-box; padding-left: 2em;\"><li>nested</li></ul></li></ul><div class=\"highlight\" style=\"box-sizing: border-box; margin-bottom: 16px;\"><pre style=\"box-sizing: border-box; font-family: ui-monospace, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 0px; padding: 16px; overflow: auto; background-color: rgb(246, 248, 250);\"><span class=\"pl-k\" style=\"color: rgb(207, 34, 46);\">func</span> <span class=\"pl-en\">main</span>() {\n    fmt.<span class=\"pl-en\">Println</span>(<span class=\"pl-s\">\"hi\"</span>)\n}</pre></div>\n",
		"## Installation\n\nRun `go install ./...` and then restart the [service](https://example.com/docs).\n\n- First *item*\n\n- Second item\n\n  - nested\n\n```\nfunc main() {\n    fmt.Println(\"hi\")\n} \n```"},
	{"<meta charset=\"utf-8\"><b style=\"font-weight:normal;\" id=\"docs-internal-guid-1234\"><h1 dir=\"ltr\" style=\"line-height:1.38;margin-top:20pt;margin-bottom:6pt;\"><span style=\"font-size:20pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">Meeting notes</span></h1><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:0pt;\"><span style=\"font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">Decision:</span><span style=\"font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> ship on Friday, see </span><a href=\"https://example.com\" style=\"text-decoration:none;\"><span style=\"font-size:11pt;font-family:Arial,sans-serif;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">the plan</span></a></p><ul style=\"margin-top:0;margin-bottom:0;padding-inline-start:48px;\"><li dir=\"ltr\" style=\"list-style-type:disc;font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;\" aria-level=\"1\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:0pt;\" role=\"presentation\"><span style=\"font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">Alice</span><span style=\"font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> owns the rollout</span></p></li></ul></b>\n",
		"# Meeting notes\n\n**Decision:** ship on Friday, see [the plan](https://example.com)\n\n```\nAlice owns the rollout \n```"},
	{"<html xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:w=\"urn:schemas-microsoft-com:office:word\">\n<head><meta http-equiv=Content-Type content=\"text/html; charset=utf-8\">\n<style>\n<!--\n /* Style Definitions */\n p.MsoNormal, li.MsoNormal, div.MsoNormal\n\t{margin:0in;\n\tfont-size:11.0pt;\n\tfont-family:\"Calibri\",sans-serif;}\nh1\n\t{mso-style-link:\"Heading 1 Char\";\n\tmargin-top:12.0pt;\n\tmargin-right:0in;\n\tmargin-bottom:0in;\n\tmargin-left:0in;\n\tfont-size:16.0pt;\n\tfont-family:\"Calibri Light\",sans-serif;\n\tcolor:#2F5496;\n\tfont-weight:normal;}\np.MsoListParagraph\n\t{margin-top:0in;\n\tmargin-right:0in;\n\tmargin-bottom:0in;\n\tmargin-left:.5in;\n\tfont-size:11.0pt;}\n@page WordSection1\n\t{size:8.5in 11.0in;}\n-->\n</style>\n</head>\n<body lang=EN-US style='word-wrap:break-word'>\n<!--StartFragment-->\n<h1>Quarterly <o:p></o:p></h1>\n<p class=MsoNormal>This is <b>bold</b> and <i>italic</i> text with a <a href=\"https://example.com\">link</a>.<o:p></o:p></p>\n<p class=MsoListParagraph style='text-indent:-.25in;mso-list:l0 level1 lfo1'><![if !supportLists]><span style='font-family:Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt \"Times New Roman\"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>First point<o:p></o:p></p>\n<p class=MsoNormal><span style='font-family:\"Courier New\"'>code_here()</span><o:p></o:p></p>\n<!--EndFragment-->\n</body>\n</html>\n",
		"# Quarterly\n\nThis is **bold** and *italic* text with a [link](https://example.com).\n\n·\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 First point\n\n`code_here()`"},
	{"<!DOCTYPE html><html><head><meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/><title></title><style type=\"text/css\">@page { size: 8.5in 11in; margin: 0.79in } p { line-height: 115%; margin-bottom: 0.1in; background: transparent } h2 { margin-top: 0.14in; margin-bottom: 0.08in; background: transparent; page-break-after: avoid } h2.western { font-family: \"Liberation Serif\", serif; font-size: 18pt; font-weight: bold } a:link { color: #000080; so-language: zxx; text-decoration: underline } code.western { font-family: \"Liberation Mono\", monospace }</style></head><body lang=\"en-US\" link=\"#000080\" vlink=\"#800000\" dir=\"ltr\"><h2 class=\"western\">Section</h2><p style=\"line-height: 100%; margin-bottom: 0in\">Text with <code class=\"western\">mono</code> and <b>strong</b>.</p><ol><li><p style=\"margin-bottom: 0in; line-height: 100%\">One</p></li><li><p style=\"margin-bottom: 0in; line-height: 100%\">Two</p></li></ol><table width=\"100%\" cellpadding=\"4\" cellspacing=\"0\"><col width=\"128*\"/><col width=\"128*\"/><tr valign=\"top\"><td width=\"50%\" style=\"border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding-top: 0.04in\"><p>A</p></td><td width=\"50%\" style=\"border: 1px solid #000000; padding: 0.04in\"><p>B</p></td></tr><tr valign=\"top\"><td width=\"50%\"><p>1</p></td><td width=\"50%\"><p>2</p></td></tr></table><p style=\"line-height: 100%; margin-bottom: 0in\"><br/></p></body></html>\n",
		"## Section\n\nText with `mono` and **strong**.\n\n1. One\n\n2. Two\n\n| A | B |\n| --- | --- |\n| 1 | 2 |"},
	{"<h1 id=\"title\">Title</h1>\n<p>Paragraph with <em>emphasis</em>, <strong>strong</strong>, <code>code</code>, and a <a href=\"http://x.y\">link</a>.</p>\n<blockquote>\n<p>Quoted line one.<br>\nQuoted line two.</p>\n</blockquote>\n<ol start=\"3\">\n<li>three</li>\n<li>four\n<ul>\n<li>nested bullet</li>\n</ul>\n</li>\n</ol>\n<pre><code class=\"language-go\">func main() {\n\tprintln(\"tab\")\n}\n</code></pre>\n<table>\n<thead>\n<tr>\n<th align=\"left\">Name</th>\n<th align=\"right\">Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td align=\"left\">a*b</td>\n<td align=\"right\">[1]</td>\n</tr>\n</tbody>\n</table>\n<hr>\n<p><img src=\"pic.png\" alt=\"alt text\"> trailing</p>\n",
		"# Title\n\nParagraph with *emphasis*, **strong**, `code`, and a [link](http://x.y).\n\n> Quoted line one.\u2028Quoted line two.\n\n1. three\n\n2. four\n\n  - nested bullet\n\n```\nfunc main() {\n\tprintln(\"tab\")\n}\n```\n\n| Name | Value |\n| --- | --- |\n| a\\*b | \\[1\\] |\n\n![](pic.png) trailing"},
}

func TestHTMLToMarkdownMatchesQt(t *testing.T) {
	for _, c := range qtConversions {
		if got := HTMLToMarkdown(c.html); got != c.md {
			t.Errorf("%q:\n got %q\nwant %q", c.html, got, c.md)
		}
	}
}
